<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <InvariantGlobalization>true</InvariantGlobalization>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>

</Project>
