/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["SetCurrentProject"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 헬스 체크 응답. */
        HealthResponse: {
            /** @description 살아 있으면 `ok`. */
            status: string;
        };
        /** @description 프로젝트 하나. 위 줄 프로젝트 선택기와 "모든 프로젝트" 요약이 쓴다. */
        ProjectItem: {
            /** @description 폴더 이름. */
            name: string;
            /** @description 전체 경로. */
            path: string;
            /**
             * Format: int32
             * @description 인덱스에 있는 세션 수. 최근 폴더에만 있으면 0.
             */
            sessionCount: number;
            /**
             * Format: date-time
             * @description 마지막 세션이 바뀐 때. 세션이 없으면 null.
             */
            lastActivity: null | string;
            /** @description 폴더가 아직 있는가. 없으면 세션만 남은 것이다. */
            exists: boolean;
        };
        /** @description 프로젝트 목록과 지금 고른 프로젝트. */
        ProjectsResponse: {
            /** @description 마지막 작업이 최근인 것부터. */
            projects: components["schemas"]["ProjectItem"][];
            /** @description 지금 프로젝트의 경로. null 이면 "모든 프로젝트". */
            current: null | string;
        };
        /** @description 지금 프로젝트를 바꾸는 요청. */
        SetCurrentProjectRequest: {
            /** @description 목록에 있는 경로. null 이면 "모든 프로젝트". */
            path: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ListProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectsResponse"];
                };
            };
        };
    };
    SetCurrentProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCurrentProjectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectsResponse"];
                };
            };
        };
    };
}
