/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListTools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetBell"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["SetCurrentProject"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetLimits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/limits/claude/statusline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["SetClaudeStatusLine"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetIndexStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/index/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RefreshIndex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/index/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RebuildIndex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{tool}/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{tool}/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SaveProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{tool}/profiles/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ApplyProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{tool}/profiles/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RemoveProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SearchSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetSessionMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExportSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["RenameSession"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DeleteSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ResumeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["SetCleanupRule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/worktrees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetWorktrees"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terminal/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListRooms"];
        put?: never;
        post: operations["OpenRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terminal/rooms/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CloseRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terminal/rooms/{id}/seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MarkRoomSeen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terminal/rooms/{id}/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["RenameRoom"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terminal/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terminal/rooms/{id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetRoomChat"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terminal/rooms/{id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SendToRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terminal/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListCommands"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terminal/external": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OpenExternalTerminal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terminal/open-folder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OpenFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 도구 하나의 로그인 상태. 토큰 값은 어디에도 없다. */
        Account: {
            /** @description 도구 id. */
            tool: string;
            /** @description CLI 가 깔려 있는가. */
            installed: boolean;
            /** @description `loggedIn` · `expiringSoon`(7일 안) · `expired` · `missing`. */
            state: string;
            /** @description 계정 이름. */
            accountLabel: null | string;
            /** @description 이메일. */
            email: null | string;
            /** @description 요금제. */
            plan: null | string;
            /**
             * Format: date-time
             * @description 다시 로그인해야 하는 때. 모르면 null.
             */
            expiresAt: null | string;
            /** @description 부가 정보. */
            notes: components["schemas"]["AccountNote"][];
            /** @description 로그인이 파일에 있어 저장·바꾸기를 할 수 있는가. Windows 자격 증명 관리자에 두는 도구는 못 한다. */
            canSaveProfiles: boolean;
            /** @description 저장한 계정. 최근 것이 앞. */
            profiles: components["schemas"]["AccountProfile"][];
        };
        /** @description 로그인 카드 한 줄 부가 정보. 문장은 화면이 `Key` 로 찾는다. */
        AccountNote: {
            /** @description 문구 키(`AuthNote_…`). */
            key: string;
            /** @description 문구의 `{0}`. 토큰 값은 들어오지 않는다. */
            argument: null | string;
        };
        /** @description 저장한 계정 하나. */
        AccountProfile: {
            name: string;
            accountLabel: null | string;
            email: null | string;
            /** Format: date-time */
            savedAt: string;
            /** Format: date-time */
            expiresAt: null | string;
        };
        /** @description "손볼 것" 한 줄. 화면이 `Kind` 를 보고 문장과 단추를 고른다. */
        Attention: {
            /** @description `account`(로그인 곧 만료·만료·없음) · `cleanup`(정리할 만한 세션) · `index`(인덱스 실패) · `plugin`(도구 플러그인 실패). */
            kind: string;
            /** @description `warn` · `bad`. */
            level: string;
            /** @description account 일 때 도구 id. */
            tool?: null | string;
            /** @description account 일 때 상태(`expiringSoon` · `expired` · `missing`). */
            state?: null | string;
            /**
             * Format: date-time
             * @description account 일 때 만료 시각.
             */
            at?: null | string;
            /**
             * Format: int32
             * @description cleanup 일 때 세션 수.
             */
            count?: null | number;
            /**
             * Format: int64
             * @description cleanup 일 때 크기 합.
             */
            bytes?: null | number;
            /** @description plugin 일 때 플러그인 이름. */
            name?: null | string;
            /** @description index·plugin 일 때 까닭. */
            detail?: null | string;
        };
        /** @description 위 줄 종 팝업. 열린 터미널 방은 `/api/terminal/rooms` 에서 따로 받는다. */
        BellResponse: {
            /** @description 손볼 것. 팝업 맨 위. */
            attention: components["schemas"]["Attention"][];
            last: null | components["schemas"]["ProjectWork"];
            /** @description 다른 프로젝트에서 하던 것. 프로젝트마다 가장 최근 것 하나, 최대 int BellEndpoints.OthersCount개. */
            others: components["schemas"]["ProjectWork"][];
        };
        /** @description 말풍선 한 칸. */
        ChatItem: {
            /**
             * Format: int64
             * @description 이 방에서 몇 번째 칸인가. 화면은 마지막으로 받은 번호 뒤만 다시 받는다.
             */
            seq: number;
            /**
             * Format: date-time
             * @description 기록에 적힌 때.
             */
            at: string;
            /** @description `me`(사람) · `ai`(답) · `tool`(도구 호출) · `result`(도구 결과. 성공·실패만 쓴다). */
            kind: string;
            /** @description 본문. 사람 글은 도구가 감싼 머리말을 벗긴 것. */
            text: string;
            /** @description tool 일 때 도구 이름. */
            tool: null | string;
            /** @description result 일 때 실패했는가. */
            error: boolean;
        };
        /** @description 말풍선 목록. */
        ChatResponse: {
            /** @description 이 방의 세션 기록을 찾았는가. 첫 메시지를 보내기 전에는 기록이 없을 수 있다(Codex 는 첫 메시지 때 만든다). */
            found: boolean;
            /**
             * Format: int64
             * @description 지금까지의 마지막 칸 번호. 다음에 `after` 로 보낸다.
             */
            last: number;
            /** @description `after` 뒤의 칸들. 처음 받을 때는 끝에서 int RoomChat.FirstPage개까지. */
            items: components["schemas"]["ChatItem"][];
        };
        /** @description 정리 기준. "골라 체크"와 요약의 "손볼 것"이 같은 값을 쓴다. */
        CleanupRule: {
            /**
             * Format: int32
             * @description 이 일수보다 오래 안 쓴 세션.
             */
            olderThanDays: number;
            /**
             * Format: int32
             * @description 이 크기를 넘는 세션.
             */
            largerThanMegabytes: number;
        };
        /** @description / 목록의 묶음. */
        CommandGroup: {
            /** @description `builtin`(도구 기본 명령) · `user`(내 명령·스킬) · `project`(이 프로젝트의 명령·스킬). */
            kind: string;
            /** @description 어디서 읽었나. 화면이 묶음 제목 옆에 보인다. */
            source: string;
            /** @description 명령들. */
            items: components["schemas"]["CommandItem"][];
        };
        /** @description / 목록 한 줄. */
        CommandItem: {
            /** @description `/` 로 시작하는 이름. */
            name: string;
            /** @description 받는 인자 모양. 없으면 빈 문자열. */
            argument: string;
            /** @description 설명 한 줄. */
            description: string;
            /** @description 화면이 있어야 하는 명령. 고르면 터미널 보기로 넘긴다. */
            terminal: boolean;
        };
        /** @description "이번 주 토큰" 막대 하나. */
        DashboardDay: {
            /**
             * Format: date
             * @description 날짜. 도구 기록의 날짜(UTC)다.
             */
            date: string;
            /**
             * Format: int64
             * @description 그날 토큰 합.
             */
            tokens: number;
        };
        /** @description 요약 화면. 열린 터미널은 `/api/terminal/rooms`, 한도는 `/api/limits`, 워크트리는 `/api/dashboard/worktrees` 에서 따로 받는다. */
        DashboardResponse: {
            /** @description 지금 프로젝트 경로. null 이면 모든 프로젝트. */
            project: null | string;
            /** @description 오늘 세션. */
            today: components["schemas"]["DashboardToday"];
            /** @description 최근 7일, 오래된 날부터. */
            week: components["schemas"]["DashboardDay"][];
            /** @description 최근 세션 최대 5개. 마지막 활동 순. */
            recent: components["schemas"]["RecentSession"][];
        };
        /** @description "오늘 세션" 타일. */
        DashboardToday: {
            /**
             * Format: int32
             * @description 오늘(이 PC 의 날짜) 바뀐 세션 수.
             */
            sessions: number;
            /**
             * Format: int32
             * @description 그 세션들의 프로젝트 수(워크트리·임시 폴더는 원래 프로젝트로 센다).
             */
            projects: number;
            /**
             * Format: int32
             * @description 어제 바뀐 세션 수.
             */
            yesterday: number;
        };
        /** @description 세션을 지우는 요청. */
        DeleteRequest: {
            /** @description 세션 파일 경로들. */
            paths: string[];
            /** @description 휴지통을 거치지 않고 바로 지울지. */
            permanent: boolean;
        };
        /** @description 지운 결과. */
        DeleteResponse: {
            /** @description 지운 경로. */
            deleted: string[];
            /** @description 못 지운 것과 까닭. 실행 중 세션은 늘 여기 온다. */
            skipped: components["schemas"]["SkippedSession"][];
        };
        /** @description 폴더를 가리키는 요청. */
        FolderRequest: {
            path: string;
        };
        /** @description 헬스 체크 응답. */
        HealthResponse: {
            /** @description 살아 있으면 `ok`. */
            status: string;
        };
        /** @description 인덱스 갱신 상태. 화면 아래 줄에 그대로 보여 준다. */
        IndexStatus: {
            /** @description 돌고 있는가. */
            running: boolean;
            /** @description 처음부터 다시 만드는 중인가. false 면 바뀐 것만 이어 읽는다. */
            rebuilding: boolean;
            /**
             * Format: int32
             * @description 끝낸 세션 수. 다시 만들 때만 센다.
             */
            done: number;
            /**
             * Format: int32
             * @description 전체 세션 수. 모르면 0.
             */
            total: number;
            /** @description 마지막 실행이 실패한 까닭. 성공했으면 null. */
            error: null | string;
            /**
             * Format: date-time
             * @description 마지막으로 끝난 때. 한 번도 안 돌았으면 null.
             */
            finishedAt: null | string;
        };
        /** @description 한도 창 하나. */
        LimitWindow: {
            /**
             * Format: int32
             * @description 창의 길이(분). 300 이면 5시간, 10080 이면 7일.
             */
            windowMinutes: number;
            /**
             * Format: double
             * @description 쓴 비율. 0~100.
             */
            usedPercent: number;
            /**
             * Format: date-time
             * @description 다시 차는 때. 지났으면 화면이 "초기화됨 · 0%"로 보여 준다.
             */
            resetsAt: null | string;
        };
        /** @description 모든 도구의 구독 한도. 도구 목록 순서. */
        LimitsResponse: {
            tools: components["schemas"]["ToolLimits"][];
        };
        /** @description 대화 한 줄. */
        MessageRow: {
            /** @description `user` · `assistant` · `tool` · `system`. */
            role: string;
            /**
             * Format: date-time
             * @description 시각.
             */
            at: string;
            /** @description 본문. 화면이 1500자에서 접는다. */
            text: string;
        };
        /** @description 대화 보기. */
        MessagesResponse: {
            /** @description 처음부터. 2000개까지. */
            messages: components["schemas"]["MessageRow"][];
            /** @description 2000개를 넘어 뒤를 잘랐는가. */
            truncated: boolean;
        };
        ModelOption: {
            id: string;
            name: string;
            description?: null | string;
        };
        /** @description 방을 여는 요청. */
        OpenRoomRequest: {
            /** @description 도구 id. */
            tool: string;
            /** @description 작업 폴더. 있어야 한다. */
            folder: string;
            /** @description 이어서 열 세션 파일. 비우면 새 대화. */
            resumePath?: null | string;
            /** @description 모델 id. 비우면 도구 설정대로. */
            model?: null | string;
            /** @description 사람이 적은 옵션 인자. 그대로 붙는다. */
            arguments?: null | string;
            /** @description 방 이름. 비우면 폴더 이름. */
            name?: null | string;
        };
        /** @description 프로필 이름을 받는 요청. */
        ProfileRequest: {
            name: string;
        };
        /** @description 프로젝트 하나. 위 줄 프로젝트 선택기와 "모든 프로젝트" 요약이 쓴다. */
        ProjectItem: {
            /** @description 폴더 이름. Claude 임시 폴더 묶음은 정해 둔 이름. */
            name: string;
            /** @description 전체 경로. 프로젝트를 가리키는 열쇠로 쓴다. */
            path: string;
            /**
             * Format: int32
             * @description 인덱스에 있는 세션 수. 묶인 워크트리 것까지 센다. 최근 폴더에만 있으면 0.
             */
            sessionCount: number;
            /**
             * Format: date-time
             * @description 마지막 세션이 바뀐 때. 세션이 없으면 null.
             */
            lastActivity: null | string;
            /** @description 폴더가 아직 있는가. 없으면 세션만 남은 것이다. */
            exists: boolean;
            /** @description 이 프로젝트로 묶은 폴더들(자기 포함). 워크트리·임시 폴더가 여기 들어온다 (ProjectGroups). */
            members: string[];
        };
        /** @description 한 프로젝트에서 가장 최근에 하던 것. */
        ProjectWork: {
            /** @description 프로젝트(묶음) 경로. */
            projectPath: string;
            /** @description 프로젝트 이름. */
            projectLabel: string;
            /** @description 그 프로젝트의 가장 최근 세션. */
            work: components["schemas"]["RecentSession"];
        };
        /** @description 프로젝트 목록과 지금 고른 프로젝트. */
        ProjectsResponse: {
            /** @description 마지막 작업이 최근인 것부터. */
            projects: components["schemas"]["ProjectItem"][];
            /** @description 지금 프로젝트의 경로. null 이면 "모든 프로젝트". */
            current: null | string;
        };
        /** @description 세션 한 줄과 그 세션에서 사람이 마지막으로 친 질문. */
        RecentSession: {
            /** @description 세션. */
            session: components["schemas"]["SessionRow"];
            /** @description 마지막으로 친 질문(한 줄로 다듬음). 사람이 친 줄이 없으면 null. */
            lastPrompt: null | string;
            /**
             * Format: date-time
             * @description 그 질문을 친 때.
             */
            lastPromptAt: null | string;
        };
        /** @description 세션 이름을 붙이거나 떼는 요청. */
        RenameRequest: {
            /** @description 세션 파일 경로. */
            path: string;
            /** @description 이름. 비우면 뗀다. */
            name: null | string;
        };
        /** @description 방 하나. */
        RoomInfo: {
            /** @description 방 id. */
            id: string;
            /** @description 도구 id. */
            tool: string;
            /** @description 작업 폴더. */
            folder: string;
            /** @description 방 이름. */
            name: string;
            /** @description `idle` · `run` · `done` · `ask`(허락 기다림, Claude 만) · `exited`. */
            state: string;
            /** @description 답이 끝났는데 아직 안 봤다. */
            unseen: boolean;
            /**
             * Format: date-time
             * @description 연 때.
             */
            startedAt: string;
            /**
             * Format: date-time
             * @description 마지막으로 답이 끝난 때.
             */
            doneAt: null | string;
            /**
             * Format: int32
             * @description 프로세스가 끝났으면 종료 코드.
             */
            exitCode: null | number;
            /**
             * @description 이 방이 속한 프로젝트 경로. 워크트리·Claude 임시 폴더는 원래 프로젝트다(ProjectGroups).
             *     방을 연 폴더에 세션이 아직 없어도 프로젝트 방 목록에 묶인다.
             */
            project: string;
        };
        /** @description 이름을 바꾸는 요청. */
        RoomNameRequest: {
            name: string;
        };
        /** @description 검색에 걸린 세션 하나와 그 안의 메시지들. */
        SearchGroup: {
            /** @description 세션. */
            session: components["schemas"]["SessionRow"];
            /** @description 최대 20개. */
            matches: components["schemas"]["SearchMatch"][];
        };
        /** @description 검색에 걸린 메시지 하나. */
        SearchMatch: {
            /** @description `user` · `assistant` · `tool` · `system`. */
            role: string;
            /**
             * Format: date-time
             * @description 메시지 시각.
             */
            at: string;
            /** @description 찾은 말 앞뒤를 자른 것. */
            snippet: string;
        };
        /** @description 검색 결과. */
        SearchResponse: {
            /** @description 세션마다 묶었다. 세션이 최근에 바뀐 것부터. */
            groups: components["schemas"]["SearchGroup"][];
            /**
             * Format: int32
             * @description 걸린 메시지 수. 서버가 200개에서 끊는다.
             */
            total: number;
        };
        /** @description 말풍선 입력칸에서 보내는 글. */
        SendRequest: {
            /** @description 여러 줄이어도 한 메시지로 들어간다. */
            text: string;
        };
        /** @description 세션 하나를 가리키는 요청. */
        SessionRequest: {
            path: string;
        };
        /** @description 세션 한 줄. */
        SessionRow: {
            /** @description 세션 파일 경로. 세션을 가리키는 열쇠로 쓴다. */
            path: string;
            /** @description 도구 id. */
            tool: string;
            /** @description 도구가 붙인 세션 id. */
            id: string;
            /** @description 붙인 이름. 없으면 첫 질문을 다듬은 것. 둘 다 없으면 빈 문자열. */
            title: string;
            /** @description 사람이 이름을 붙였는가. */
            named: boolean;
            /** @description 프로젝트 폴더. 모르면 null. */
            projectPath: null | string;
            /** @description 보여 줄 프로젝트 이름. 이름이 겹치면 상위 폴더까지 붙인다. */
            projectLabel: string;
            /**
             * Format: date-time
             * @description 시작한 때.
             */
            startedAt: string;
            /**
             * Format: date-time
             * @description 마지막으로 바뀐 때.
             */
            modifiedAt: string;
            /**
             * Format: int64
             * @description 파일 크기.
             */
            sizeBytes: number;
            /**
             * Format: int32
             * @description 사람이 보낸 메시지 수.
             */
            userMessages: number;
            /**
             * Format: int32
             * @description 모델이 보낸 메시지 수.
             */
            assistantMessages: number;
            /** @description 지금 실행 중인가. 실행 중이면 지울 수 없다. Claude 만 안다. */
            active: boolean;
            /** @description Codex 가 보관함으로 옮긴 세션인가. */
            archived: boolean;
            /** @description 프로젝트 폴더가 없거나 사라졌는가. */
            orphan: boolean;
        };
        /** @description 세션 목록. */
        SessionsResponse: {
            /** @description 마지막으로 바뀐 것부터. */
            sessions: components["schemas"]["SessionRow"][];
            /** @description 정리 기준. */
            cleanup: components["schemas"]["CleanupRule"];
        };
        /** @description 지금 프로젝트를 바꾸는 요청. */
        SetCurrentProjectRequest: {
            /** @description 목록에 있는 경로. null 이면 "모든 프로젝트". */
            path: null | string;
        };
        /** @description Claude 상태줄 등록을 켜고 끄는 요청. */
        SetStatusLineRequest: {
            /** @description 켤지. */
            enabled: boolean;
        };
        /** @description 못 지운 세션. */
        SkippedSession: {
            path: string;
            reason: string;
        };
        /** @description 도구 하나. 화면이 도구 칩과 글자 표시를 그린다. */
        ToolItem: {
            /** @description 도구 id. 사용량 등에서 도구를 고를 때 이 값을 보낸다. */
            id: string;
            /** @description 이름. */
            title: string;
            /** @description 한 글자 표시. */
            initial: string;
            /**
             * Format: int32
             * @description 표시 순서. 작은 것이 앞.
             */
            order: number;
            /** @description 색. 하나면 단색, 둘 이상이면 그 순서의 그라데이션. */
            colors: string[];
        };
        /** @description 도구 하나의 구독 한도. */
        ToolLimits: {
            /** @description 도구 id. */
            tool: string;
            /** @description `statusline`(Claude 상태줄) · `sessions`(Codex 세션 기록) · `none`(읽을 길이 없는 도구). */
            source: string;
            /** @description Claude 만: 상태줄 등록이 켜져 있는가. 다른 도구는 null. */
            enabled: null | boolean;
            /**
             * Format: date-time
             * @description 값이 적힌 때. 아직 받은 적이 없으면 null.
             */
            at: null | string;
            /** @description 창 목록. 짧은 창부터. */
            windows: components["schemas"]["LimitWindow"][];
            /** @description 요금제 이름. 모르면 null. */
            plan: null | string;
        };
        /** @description 그래프 한 칸. 하루·한 주(월요일 시작)·한 달(1일 시작). */
        UsageBucket: {
            /**
             * Format: date
             * @description 칸의 첫날.
             */
            start: string;
            /** @description 그 칸의 합. */
            tokens: components["schemas"]["UsageTokens"];
        };
        /** @description 사용량 탭 한 화면. */
        UsageResponse: {
            /**
             * Format: date
             * @description 기록이 있는 첫날. 기록이 없으면 null.
             */
            firstDay: null | string;
            /**
             * Format: date
             * @description 오늘. 날짜는 UTC 기준이다. 세션 기록의 날짜가 UTC 로 적힌다.
             */
            today: string;
            /** @description 오늘 · 최근 7일 · 최근 30일 합. */
            totals: components["schemas"]["UsageTotals"];
            /** @description 그래프 칸. 오늘이 든 칸까지 빈 칸 없이 이어진다. */
            buckets: components["schemas"]["UsageBucket"][];
            /** @description 많이 쓴 프로젝트 10개. */
            byProject: components["schemas"]["UsageShare"][];
            /** @description 모델 전부. 많이 쓴 것부터. */
            byModel: components["schemas"]["UsageShare"][];
        };
        /** @description 프로젝트별·모델별 한 줄. */
        UsageShare: {
            /** @description 프로젝트 경로 또는 모델 이름. */
            key: string;
            /** @description 보여 줄 이름. 프로젝트는 폴더 이름이고, 겹치면 상위 폴더까지 붙인다. */
            label: string;
            /** @description 합. */
            tokens: components["schemas"]["UsageTokens"];
            /**
             * Format: double
             * @description 전체에서 차지하는 비율. 0~1.
             */
            share: number;
        };
        /** @description 토큰 네 갈래와 합. */
        UsageTokens: {
            /** Format: int64 */
            input: number;
            /** Format: int64 */
            output: number;
            /** Format: int64 */
            cacheCreate: number;
            /** Format: int64 */
            cacheRead: number;
            /** Format: int64 */
            total: number;
        };
        /** @description 최근 기간 합. */
        UsageTotals: {
            today: components["schemas"]["UsageTokens"];
            last7Days: components["schemas"]["UsageTokens"];
            last30Days: components["schemas"]["UsageTokens"];
        };
        /** @description 워크트리 하나. 저장소의 메인 작업 폴더는 넣지 않는다. */
        WorktreeItem: {
            /** @description 저장소 이름(폴더 이름). */
            repo: string;
            /** @description 저장소 메인 작업 폴더. */
            repoPath: string;
            /** @description 워크트리 폴더. */
            path: string;
            /** @description 브랜치. 분리된 HEAD 면 null. */
            branch: null | string;
            /** @description 폴더가 아직 있는가. git 에는 남았는데 폴더를 지운 경우 false. */
            exists: boolean;
            /**
             * Format: int32
             * @description 커밋 안 한 변경 파일 수(새 파일 포함). 못 읽었으면 null.
             */
            changes: null | number;
            /** @description 앞뒤를 잰 기준 브랜치(origin 의 기본 브랜치, 없으면 main·master). 못 찾았으면 null. */
            baseBranch: null | string;
            /**
             * Format: int32
             * @description 기준 브랜치에 없는 이 워크트리의 커밋 수.
             */
            ahead: null | number;
            /**
             * Format: int32
             * @description 이 워크트리에 없는 기준 브랜치의 커밋 수.
             */
            behind: null | number;
            /**
             * Format: date-time
             * @description 마지막 커밋 시각.
             */
            lastCommitAt: null | string;
            /** @description 마지막 커밋 제목. */
            lastCommit: null | string;
        };
        /** @description 워크트리 목록. */
        WorktreesResponse: {
            /** @description 마지막 커밋이 최근인 것부터. */
            worktrees: components["schemas"]["WorktreeItem"][];
            /** @description git 을 찾지 못했다. 그러면 목록은 비어 있다. */
            gitMissing: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ListTools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolItem"][];
                };
            };
        };
    };
    GetBell: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BellResponse"];
                };
            };
        };
    };
    ListProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectsResponse"];
                };
            };
        };
    };
    SetCurrentProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCurrentProjectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectsResponse"];
                };
            };
        };
    };
    GetLimits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LimitsResponse"];
                };
            };
        };
    };
    SetClaudeStatusLine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetStatusLineRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LimitsResponse"];
                };
            };
        };
    };
    GetIndexStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexStatus"];
                };
            };
        };
    };
    RefreshIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexStatus"];
                };
            };
        };
    };
    RebuildIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexStatus"];
                };
            };
        };
    };
    ListAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
        };
    };
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SaveProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApplyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RemoveProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetUsage: {
        parameters: {
            query?: {
                grain?: string;
                tool?: string;
                project?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageResponse"];
                };
            };
        };
    };
    ListSessions: {
        parameters: {
            query?: {
                tool?: string;
                project?: string;
                days?: number;
                minMegabytes?: number;
                orphans?: boolean;
                archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionsResponse"];
                };
            };
        };
    };
    SearchSessions: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    GetSessionMessages: {
        parameters: {
            query: {
                path: string;
                tools?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagesResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExportSession: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RenameSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeleteSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
        };
    };
    ResumeSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SetCleanupRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleanupRule"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanupRule"];
                };
            };
        };
    };
    GetDashboard: {
        parameters: {
            query?: {
                project?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
    GetWorktrees: {
        parameters: {
            query?: {
                project?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorktreesResponse"];
                };
            };
        };
    };
    ListRooms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomInfo"][];
                };
            };
        };
    };
    OpenRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenRoomRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomInfo"];
                };
            };
        };
    };
    CloseRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MarkRoomSeen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RenameRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomNameRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListModels: {
        parameters: {
            query: {
                tool: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOption"][];
                };
            };
        };
    };
    GetRoomChat: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SendToRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListCommands: {
        parameters: {
            query: {
                tool: string;
                folder?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandGroup"][];
                };
            };
        };
    };
    OpenExternalTerminal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenRoomRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OpenFolder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
