namespace Daiso.Host.Shared;

/// <summary>
/// 세션 기록에서 사람 자리에 들어 있지만 사람이 친 글이 아닌 줄을 가린다.
/// 도구가 끼워 넣는 알림(<c>&lt;task-notification&gt;</c>·<c>&lt;system-reminder&gt;</c>), 슬래시 명령의 원문과 출력,
/// 대화를 줄인 뒤 이어 붙이는 요약("This session is being continued…") 같은 것들이다.
/// 2026-10-06 하루치 기록에서 사람 자리 387줄 가운데 이런 줄이 섞여 "마지막 질문"을 차지하던 것을 보고 정했다.
/// </summary>
public static class PromptNoise
{
    private static readonly string[] Prefixes =
    [
        "This session is being continued from a previous conversation",
        "Caveat: The messages below were generated by the user while running local commands",
        "[Request interrupted by user",

        // Codex 가 사람 글 앞에 붙이는 머리말. 표시 글이 이것으로 시작하면 사람 글(아래 표시 뒤)이 잘려 나간 것이다
        "# Context from my IDE setup:",
        "# Files mentioned by the user:",
        "# Review comments selected by the user:",

        // Codex 가 대화 첫머리에 사람 자리로 넣는 지침 전문
        "# AGENTS.md instructions",
    ];

    /// <summary>Codex 가 사람 글 바로 앞에 두는 표시. 그 앞은 IDE 맥락·첨부 파일·리뷰 댓글이다(2026-10-07 인덱스의 사람 줄 759개).</summary>
    private const string CodexRequest = "## My request for Codex:";

    /// <summary>도구가 사람 글을 감싼 머리말을 벗긴다. 감싸지 않았으면 그대로.</summary>
    public static string Body(string text)
    {
        ArgumentNullException.ThrowIfNull(text);

        var at = text.IndexOf(CodexRequest, StringComparison.Ordinal);
        return at < 0 ? text : text[(at + CodexRequest.Length)..].Trim();
    }

    /// <summary>사람이 친 글이 아니면 true. 빈 글도 true. <see cref="Body"/> 로 벗긴 뒤에 묻는다.</summary>
    public static bool IsNoise(string? text)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return true;
        }

        var head = text.TrimStart();

        // 도구가 붙이는 줄은 태그로 시작한다. 사람이 "<div>" 처럼 시작하는 일은 드물고, 그래도 다음 질문이 대신 보인다
        if (head.Length > 1 && head[0] == '<' && (char.IsAsciiLetter(head[1]) || head[1] == '/'))
        {
            return true;
        }

        return Prefixes.Any(prefix => head.StartsWith(prefix, StringComparison.Ordinal));
    }
}
