namespace Daiso.Host.Shared;

/// <summary>
/// 세션 기록에서 사람 자리에 들어 있지만 사람이 친 글이 아닌 줄을 가린다.
/// 도구가 끼워 넣는 알림(<c>&lt;task-notification&gt;</c>·<c>&lt;system-reminder&gt;</c>), 슬래시 명령의 원문과 출력,
/// 대화를 줄인 뒤 이어 붙이는 요약("This session is being continued…") 같은 것들이다.
/// 2026-10-06 하루치 기록에서 사람 자리 387줄 가운데 이런 줄이 섞여 "마지막 질문"을 차지하던 것을 보고 정했다.
/// </summary>
public static class PromptNoise
{
    private static readonly string[] Prefixes =
    [
        "This session is being continued from a previous conversation",
        "Caveat: The messages below were generated by the user while running local commands",
        "[Request interrupted by user",
    ];

    /// <summary>사람이 친 글이 아니면 true. 빈 글도 true.</summary>
    public static bool IsNoise(string? text)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return true;
        }

        var head = text.TrimStart();

        // 도구가 붙이는 줄은 태그로 시작한다. 사람이 "<div>" 처럼 시작하는 일은 드물고, 그래도 다음 질문이 대신 보인다
        if (head.Length > 1 && head[0] == '<' && (char.IsAsciiLetter(head[1]) || head[1] == '/'))
        {
            return true;
        }

        return Prefixes.Any(prefix => head.StartsWith(prefix, StringComparison.Ordinal));
    }
}
